version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: make

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

  release:
    docker:
      - image: circleci/golang:1.14

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
