name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.16.0'
          check-latest: false
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # The version of golangci-lint to use.
          # Note: We cannot upgrade to >= 1.48 because it uses the gofmt in go 1.19 instead of version
          # of go configured in the workflow. See: https://github.com/golangci/golangci-lint-action/issues/535
          version: v1.47.3
